# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Ding
email: ding@dingphil.com
description: Homepage
baseurl: "" # the subpath of your site, e.g. /blog
url: "httsp://www.dingphil.com" # the base hostname & protocol for your site, e.g. http://example.com

# Scoial links
github_username:  ding27
zhihu_username: shannon403
# twitter_username:   your_name
# facebook_username:  your_name
# dribbble_username:  your_name

# Build settings
markdown: kramdown
# theme: jekyll-theme-mint
remote_theme: ding27/jekyll-theme-mint #for GitHub
plugins:
  - jekyll-feed

gems:
  - jekyll-email-protect

gems: [jekyll-paginate]
# maximum number of Posts youâ€™d like to be displayed per-page in the generated site
paginate: 25
# You may also specify the destination of the pagination pages:
paginate_path: "/page:num/"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
